name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment you would like to deploy this service to
        options:
          - DEV

jobs:
  init:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run Unit Test
        run: go test -race -cover -v ./...
  
  migration:
    name: Run Pending Migration
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run Pending Migration(s)
        run: migrate -database ${{ secrets.POSTGRESQL_URL }} -path migrations  up

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: [init, migration]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create app.env File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_NAME: dating
          envkey_PORT: ${{ vars.PORT }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_DB_HOST: ${{ vars.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_USER: ${{ vars.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_SSLMODE: ${{ vars.DB_SSLMODE }}
          envkey_DB_NAME: dating
          file_name: app.env
          fail_on_empty: false

      - name: Setup Cloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/dating:${{ github.ref_name }} --build-arg VERSION=${{ github.ref_name }} .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/dating:${{ github.ref_name }}

      - name: Deploy to Cloud Run
        id: gohibeesh
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: dating-app
          image: gcr.io/${{ vars.GCP_PROJECT_ID }}/dating:${{ github.ref_name }}
          region: us-west1

      - name: Show Output
        run: echo ${{ steps.gohibeesh.outputs.url }}